export const PORT = process.env.PORT || 3000;
export const BACKEND = process.env.BACKEND || "http://localhost";
export const MONGO_DB = process.env.MONGO_DB || "";
export const SECRET = process.env.SECRET || "123456789";
export const UPLOAD_TO = "public/upload";
export const MQTT = process.env.MQTT || "";
export const TOPIC_NOTIFICATION = "notifications";
export const TOPIC_NOTIFICATION_USER = "notification";
export const TOPIC_MESSAGE = "message";
